feat: 가족 연동 API 추가
POLZZAK/POLZZAK-BackEnd pull request #10
Opened 2023-05-14 10:10 UTC by yeongchan1228

# 📒 작업 내용
### 1. 가족 연동 API 추가
- 연동할 사용자 닉네임 검색
- 연동 신청
- 연동 승인
- 연동 거절
- 연동 취소
- 연동된 사용자 목록 조회
- 연동 신청한 사용자 목록 조회
- 나에게 연동 신청한 사용자 목록 조회

### 2. 사용자 조회 API 수정

# 💬참고 사항
- family_temp_map 테이블에 연동 요청 정보를, family_map 테이블에 연동 완료한 정보 저장했습니다.

2023-05-14 15:30 UTC, jihoon-jang requested changes
family_temp_map이라는 테이블명이 와닿지 않는데 family_request 라던가 다른 이름은 어떨까요?

중복되는 로직이 메소드명에 따라 생성되고 있는데 공통 로직으로 합치는 것은 어떻게 생각하시나요?

like 검색 관련하여 확인 부탁드립니다.

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/dto/MemberDto.java
> +}
UserDto와 차이가 뭔가요?

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/repository/MemberRepository.java
> +
기획에서 like 검색을 요청한 건가요?

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/dto/FamilyMemberDto.java
> +) {
MemberDto랑 같은 속성을 가지고 있는데 패키지 별로 dto를 공유 안 하시는 것으로 생각 중이신가요?

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
username이 아닌 Member나 MemberDto를 반환하는 resolver를 만들어 쓰는 것은 어떨까요?

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
두 메소드가 같은 동작을 하는데 guardian, kid에 따라 두 개의 메소드로 나누는 것은 불필요하다고 생각합니다.

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +}
boolean 값을 반환하는 메소드는 is~~~ 메소드명으로 변경하는 것은 어떨까요

2023-05-14 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
이름을 적절히 지어주고 하나로 합치는 것이 좋을 것 같습니다.

2023-05-15 03:38 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/dto/MemberDto.java
> +}
userDto -> auth 관련 정보 포함, memberDto -> 사용자 정보만을 담당합니다.

2023-05-15 03:39 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/repository/MemberRepository.java
> +
제가 생각했을 땐, 닉네임이 test, test1, test2, test3, uptest4 인 5명의 사용자가 있고 test를 검색했을 경우 다 검색되어야 한다고 생각해서 like 넣었고 기획자분께 확인 중입니다.

2023-05-15 03:39 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/dto/FamilyMemberDto.java
> +) {
네

2023-05-15 03:40 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
Jwt의 사용 이점은 인증하는 과정에서 store를 안 쓰는 점에서 있다고 생각합니다. member, memberDto를 반환하게 되면 member 테이블에서 조회가 일어나야 하므로, jwt를 쓰는 장점이 없다고 생각해요.

2023-05-15 03:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
`getKidDtoList`에서는 `userService.findMemberByMemberId(familyMap.getKidId())` kidId로 조회,
`getGuardianDtoList`에서는 `userService.findMemberByMemberId(familyMap.getGuardianId())` guardianId로 조회합니다.

같은 동작을 하나요?

2023-05-15 03:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +}
수정했습니다.

2023-05-15 03:43 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
restful api 및 method는 하나의 책임, 역할을 수행하는게 좋다고 생각합니다.
reject은 거절, cancel은 취소를 담당하고 이를 합칠 경우, 추후 확장 및 유지 보수를 진행해야 할 때, 오히려 안 좋지 않을까요?

2023-05-15 03:51 UTC, yeongchan1228 commented
`DB 변경이 일어나는 모든 메소드에 트랜잭션을 다시는 것 같은데 나중을 생각한다면 꼭 필요한 메소드로 한정하는 것이 좋아 보입니다.`
현재, jpa 연관 관계 조회는 Lazy Loading으로 진행하고 있고,  Transaction 범위 내에서만 지연 조회가 가능해서 조회 부분에는 Transactional(readOnly=true) 를 적용해 부가적인 작업은 제외하고 있습니다. 또한, 트랜잭션은 하나의 작업 단위임을 명시적으로 나타낼 수 있어 붙이고 있습니다. 
지연 로딩 측도 생각하시고 꼭 필요한 범위에서만 Transaction을 달아야 한다고 말씀하신걸까요?? 해결 방법과 꼭 필요한 범위 내에서만 Transaction을 다는 것의 이점에 대해서 말씀해주시면 좋을 것 같습니다!

2023-05-15 04:00 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/dto/MemberDto.java
> +}
UserDto의 nickname이나 profileUrl이 사용되는 곳이 있을까요?

2023-05-15 04:05 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/dto/FamilyMemberDto.java
> +) {
예를 들어 도장판에서 멤버 정보를 내려야 한다면 도장판 패키지에 멤버dto를 생성하여 응답을 내리게 되나요?

2023-05-15 04:06 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
service에서 조회를 하고 있는데 resolver에서 조회하는 거랑 무슨 차이가 있을까요

2023-05-15 04:06 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
memberId로 조회하는 로직이 같은 로직이라고 생각합니다 ㅎㅎ;

2023-05-15 04:10 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
네네 맞습니다.
이 메소드가 하는 역할이 멤버의 요청 정보를 삭제하는 로직인데 호출되는 곳이 다르다고 2개로 나뉜게 이해가 되지 않습니다.
거절, 취소를 합치자는 의미가 아니고 삭제 메소드를 나눌 필요가 있냐는 뜻이었습니다~

2023-05-15 04:13 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/dto/MemberDto.java
> +}
UserDto를 사용하고 있지 않아서 삭제했습니다.

2023-05-15 04:14 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/dto/FamilyMemberDto.java
> +) {
네

2023-05-15 04:14 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
LoginUsernameResolver가 username을 가져오는 역할이 아닌, Jwt 검증 후 payload에 담긴 값을 가져오는 resolver입니다.

2023-05-15 04:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
kidId, guardianId를 memberId로 받아서 메서드를 합치면, 메서드 명으로 어떤 member의 List가 넘어오는지 명시적으로 확인이 힘들지 않을까요? 
또, 추후에 guardianList를 받아오는 과정에서 filter 가 추가 되거나 하는 상황이 생기면 결국 메서드를 나눠야 하지 않을까요?

이런 메서드도 하나로 합치는 이점을 알려주세요.

2023-05-15 04:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
reject이냐, cancel이냐는 senderId와 receiverId가 어떤 것이 되느냐 하는 차이도 있습니다. 삭제 메서드를 하나로 합치면, 결국 sender와 receiver를 나눠서 넣어줘야 하는 1개의 depth가 더 늘어나야 하는데 굳이 `familyTempMapRepository.deleteBySenderIdAndReceiverId(findMember.getId(), targetId);` 해당 부분을 하나의 메서드로 뺼 필요가 있을까요?

2023-05-15 04:27 UTC, jihoon-jang commented
> `DB 변경이 일어나는 모든 메소드에 트랜잭션을 다시는 것 같은데 나중을 생각한다면 꼭 필요한 메소드로 한정하는 것이 좋아 보입니다.` 현재, jpa 연관 관계 조회는 Lazy Loading으로 진행하고 있고, Transaction 범위 내에서만 지연 조회가 가능해서 조회 부분에는 Transactional(readOnly=true) 를 적용해 부가적인 작업은 제외하고 있습니다. 또한, 트랜잭션은 하나의 작업 단위임을 명시적으로 나타낼 수 있어 붙이고 있습니다. 지연 로딩 측도 생각하시고 꼭 필요한 범위에서만 Transaction을 달아야 한다고 말씀하신걸까요?? 해결 방법과 꼭 필요한 범위 내에서만 Transaction을 다는 것의 이점에 대해서 말씀해주시면 좋을 것 같습니다!

트랜잭션이 하나의 작업 단위인 것은 맞지만, 트랜잭션이 과도하게 많으면 처리량이 떨어질 수 있는데요
작업해주신 내용 보면 모든 DB 변경 작업에 트랜잭션이 다 붙어 있어서요
중요한 로직(회원 가입, 결제 등)에만 붙이는 것이 좋을 것 같다고 생각됩니다.

2023-05-15 04:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
username을 resolver에서 반환하면 이 값으로 sevice에서 조회를 하는데요
제 생각에는 어차피 조회를 할거면 resolver에서 하는 것이 낫다고 생각했습니다.
반환받은 username은 대부분 member 조회를 하는데에 쓰이지 않나요?

2023-05-15 04:34 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
꼭 명시적으로 확인이 필요할까요..? 저는 호출하는 상위 메소드까지 타고 올라가서 확인해도 괜찮다고 생각합니다.
filter가 추가된다 하더라도 FamilyMemberDto 리스트를 받아오는 로직까지는 같은 동작을 하잖아요.
그러면 리스트를 받고 필터링을 하면 되지 않나요?

프로젝트가 커지면 오히려 가독성을 해친다고 생각합니다.
만약 member type이 2개가 아닌 여러 개인 경우도 모두 추가하실 생각이신가요

2023-05-15 04:34 UTC, yeongchan1228 commented
![image](https://github.com/POLZZAK/POLZZAK-BackEnd/assets/79392304/10abf1d1-55d6-4d04-8e43-8ab93ba0a82d)

`트랜잭션이 하나의 작업 단위인 것은 맞지만, 트랜잭션이 과도하게 많으면 처리량이 떨어질 수 있는데요`: jpa 구현체에 조회 시 @Transactional(readOnly = true)로 동작합니다. 즉, 단순 조회에서도 트랜잭션을 활용해서 조회한다는 것을 알 수 있죠.  Repository에서 query Method로 쿼리를 작성하고 @Query를 사용해서 쿼리를 작성해도 구현체 내에서 @Transactional이 걸리는데 구현체를 저희가 직접 구현하실 생각이신가요?

2023-05-15 04:36 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
@LoginUsername은 인증을 하는 어노테이션으로 사용하고 있습니다. 즉, 요청한 사용자의 정보가 필요 없지만 인증은 해야할 경우에도 붙여서 사용하죠. 인증한 사용자 정보가 필요 없는 경우에도 Resolver에서 Member로 반환한다면 불필요한 조회 작업이 추가되지 않나요?

2023-05-15 04:42 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
음 삭제 케이스가 2개가 아닌 여러 개를 바라보고 설계한다면 합치는 것이 무조건 좋다고 생각했는데요.
지금 같은 경우는 2가지 경우만 있어서 말씀대로 유지하셔도 될 것 같네요

2023-05-15 04:42 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
getKidDtoList, getGuardianDtoList는 각각 kid와 guardian Dto List를 가져오는 책임을 가지고 있습니다. 즉, 그 과정에서 발생하는 검증, filter 등의 조회도 이루어지고요.

`FamilyMemberDto 리스트를 받아오는 로직까지는 같은 동작을 하잖아요.`: kidId로 조회하냐, guardianId로 조회하냐 차이가 있죠. 메서드를 합치면, 이 부분을 flag 인자로 받아와야 하는데 프로젝트가 커지거나 타입이 늘어날 경우에도 flag 인자로 넣어주는 부분에서의 처리가 늘어나는 것은 동일하죠.

`그러면 리스트를 받고 필터링을 하면 되지 않나요?`: 이 부분을  getFamilyMemberDtos 메소드에서 하실건가요? 그러면 하나의 메소드에서 키드 filter, 보호자 filter 등 많은 코드가 추가 될거고 그러면 메소드를 또 분리해야 하는데 depth가 깊어져서 오히려 가독성이 떨어질 것 같네요.

2023-05-15 04:43 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
멤버 정보가 필요 없으면 loginusername을 쓰고 멤버가 필요하면 member resolver를 사용하는 것으로 생각했는데 혹시 1개의 resolver만 사용하는 것으로 오해하신 걸까요
2개의 resolver를 사용처에 맞게 쓰자는 의미였습니다.

2023-05-15 04:49 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/family/controller/FamilyRestController.java
> +			SearchedMemberListResponse.from(familyMapService.getSearchedMemberByNickname(username, nickname))));
2개로도 생각을 해보았는데, controller 단에서 entity인 Member를 받는 것은 말이 안 된다고 생각하고, memberDto를 사용해서 service로 넘겨주는 것 보단, Member를 조회하는 작업을 Service에서 해서 Member 객체를 사용하는 것이 추후 Member 정보 추가되거나 메소드 별로 사용하는 Member 정보가 다를 때 더 좋을 것 같네요.

이 부분은 추후 개발이 완료되면 리팩토링할 부분으로 생각하면 좋을 것 같네요.

2023-05-15 04:50 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/family/service/FamilyMapService.java
> +	}
1. memberId로 조회
2. entity -> dto
3. 타입에 맞게 filter 
이렇게 구현하고 메소드로 적절히 묶고 푸는 것을 생각했는데 편한대로 하시죠 ㅎㅎ

2023-05-15 04:52 UTC, jihoon-jang commented
> 

저는 메소드에 걸린 트랜잭션 말한거였어요

2023-05-15 05:01 UTC, yeongchan1228 commented
> > 
> 
> 저는 메소드에 걸린 트랜잭션 말한거였어요

@메서드에 Transactional을 명시해서 트랜잭션 범위를 맞춰, 쿼리에 대한 각각의 트랜잭션 동작을 하나로 묶습니다. 이러면 Lazy Loading 과정에서 에러가 발생한 위험과 하나의 논리적인 작업 단위로 맞추려는 의도입니다.
`트랜잭션이 하나의 작업 단위인 것은 맞지만, 트랜잭션이 과도하게 많으면 처리량이 떨어질 수 있는데요`: 결국 모든 쿼리 작업은 Transation으로 작업이 진행되는데 메서드 상에서 제거한다고 이 부분이 수정되나요?

2023-05-15 05:07 UTC, jihoon-jang approved these changes

2023-05-15 05:16 UTC, merged