도장, 미션 관련 기능 추가
POLZZAK/POLZZAK-BackEnd pull request #12
Opened 2023-05-20 02:44 UTC by jihoon-jang

# 📒 작업 내용
1. 도장, 도장판, 미션, 미션 완료 요청 기능 추가
2. 문서 작성을 위한 테스트 코드 작성
3. Member 쪽 관련 필요 메소드 생성

# 💬참고 사항
- 작은 단위로 PR을 올려야 리뷰에 대한 피로가 적을텐데 도장판이라는 기능에 다 묶여 있어서 한 번에 올린 점 양해 부탁드립니다. 코드 중 이해가 되지 않는 부분은 따로 말씀 부탁드립니다.
- 개입하는 화면이 너무 많아 빠진 값이나 API가 있다면 추가로 작업할 예정입니다.
- 테스트 코드 중 anyLong()이 동작하지 않고 있는데 혹시 아는 것이 있으시면 공유 부탁드립니다.

2023-05-21 10:18 UTC, yeongchan1228 requested changes
1. @Setter를 사용해서 setXXX()로 Entity의 값을 수정하지 말고, 명확한 메서드를 사용해서 필드 값을 변경하는게 좋아 보이네요. -> setXXX를 사용하면 어떻게 변경되는지 와 닿지 않고 setXXX로 열어 두시면 어디서든 접근해서 변경해버릴 수 있을 것 같아요. 검증 부분도 설정한 메서드에 넣어서 필드 값의 변경 검증 책임을 entity에서 가지고 있는 게 좋아보여요.

2. 매개변수 값에 final을 붙여서 사용되는 값의 변경을 막는 게 좋아보이네요.
`매개변수를 final로 선언함으로써 인자로 들어온 값에 대한 데이터의 정합성을 유지 할 수 있다.`

3. 현재 미션과 스탬프 보드는 같은 생명 주기를 가지고 있는 것 같은데 도메인으로 분리하신 이유가 궁금하네요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +	}
private 메서드는 하위로 내려주시면 좋을 것 같아요.
public 메서드가 상위에 존재해야 해당 Service가 어떤 메서드를 외부로 제공할 수 있는지 한 눈에 보여서요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +	public ResponseEntity<?> createStampBoard(
ResponseEntity에 와일드 카드로 명시하는 것보다 createStampBoard는 ApiResponse 타입으로만 응답하니`ResponseEntity<ApiResponse>`로 하시는 게 좋아보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +		}
해당 코드가 중복되고 있는데 userService에 Kid면 `throw new PolzzakException(ErrorCode.FORBIDDEN);` 예외를 던지는 메서드로 처리해주시면 좋을 것 같아요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
guardian에 대한 모든 가족들을 찾아와서 kidId 값이 존재하는 지 확인하는 것보다 familyMap에 대해서 exist 쿼리를 날리는 게 더 효율적이지 않을까요?

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +@RequestMapping("/api/v1/stamp")
url을 stamp 단수형으로 하신 이유가 있을까요?

restful api 규칙: `URI에 작성되는 영어를 복수형으로 작성한다.`

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +		@RequestParam boolean isInProgress
제가 이해한 게 맞다면 해당 값이 true,  false 냐에 따라서 진행 중인 스탬프 보드판들을 반환하는 것 같은데,
이 부분을 `StampBoard.Status`로 받지 않는 이유가 있을까요? 해당 값으로 받아서 조회하는 게 스탬프 보드판 상태에 따른 조회에 더 적합한 것 같네요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
if / else 는 안티패턴인데 다음과 같이 수정하는 것이 어떠실까요?
```java
if (partnerMemberId == null) {
	return families;
}
return families.stream()
   .filter(family -> family.memberId() == partnerMemberId)
   .toList();
```

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		List<FamilyMemberDto> filteredFamilies = getFilteredFamilies(families, partnerMemberId);
`getFilteredFamilies` 해당 메서드명을 보고 무엇에 의해 필터된 가족들인지 파악하기 어렵네요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
이 부분을 다음과 같이 작성하시는게 더 가독성이 좋아보여요.

```java
List<StampBoard> stampBoards = xxx(member, partnerId);

private List<StampBoard> xxx(final MemberDto member, final long partnerId) {
   if (member.isKid()) {
	return getStampBoards(partnerId, member.memberId());
   }
   return getStampBoards(member.memberId(), partnerId);
}
```

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +	}
```java
if (isInProgress) {
	stampBoards.stream()
		.filter(stampBoard -> StampBoard.Status.getProgressStatuses().contains(stampBoard.getStatus()))
		.map(StampBoardSummary::from)
		.toList();
}

return stampBoards.stream()
	.filter(stampBoard -> stampBoard.getStatus() == StampBoard.Status.REWARDED)
	.map(StampBoardSummary::from)
	.toList();
}
```
이런 식으로 작성하는 게 더 나을 것 같아요...

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		stampBoardRepository.delete(stampBoard);
StampBoard와 연관 관계를 맺고 있는 Entity가 다음과 같은데 delete()를 사용하면 최악의 경우 이 부분에서 수 백개의 삭제 쿼리가 발생하지 않을까요?

```java
@Where(clause = "is_active = true")
@OneToMany(mappedBy = "stampBoard", cascade = CascadeType.ALL, orphanRemoval = true)
private final List<Mission> missions = new ArrayList<>();
@OneToMany(mappedBy = "stampBoard", cascade = CascadeType.ALL, orphanRemoval = true)
private final List<Stamp> stamps = new ArrayList<>();
@OneToMany(mappedBy = "stampBoard", cascade = CascadeType.ALL, orphanRemoval = true)
private final List<MissionComplete> missionCompletes = new ArrayList<>();
```

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
이 부분은 삭제 요청에 대한 검증을 하는 메서드로 빼주시는게 좋아보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
Http의 put method를 사용하시는데, 같지 않으면 업데이트 한다 = patch 메서드의 역할 같습니다.

기획에 다음과 같이 입력을 정의해두었고, Request에서도@NotBlank로 막으셔서 클라이언트에서는 name, reward 등의 값이 반드시 넘어와 그대로 업데이트 하는 것이 나은 선택지 같네요.
```
아이 정보, 도장판 이름, 보상, 설정한 도장 개수, 찍혀 있는 도장의 개수, 설정했던 미션 목록을 넘겨줘야 합니다.

@NotBlank @Length(min = 2, max = 20) String name,
@NotBlank @Length(min = 1, max = 30) String reward,
@Nonnull List<MissionDto> missions
```

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/service/MissionService.java
> +		missionRepository.saveAll(newMissions);
이 부분도 mission 테이블에서 stampBoardId에 대해서 Bulk 쿼리로 이전 값을 삭제하고 다시 insert 하는 것이 나아 보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampService.java
> +		}
이 부분도 마찬가지로 스탬프 생성에 대한 Validate 역할을 하는 메서드로 분리하는 게 가독성이 좋아보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampService.java
> +				.stampBoard(stampBoardService.getStampBoard(stampBoardId))
`stampBoardService.getStampBoard(stampBoardId)` 다시 가져오시는 이유가 있을까요?

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampService.java
> +		int stampCount = Math.min(requestStampCount, remainingStampCount);
SRP에 적합하지 않은 것 같아요. 저장해야 할 stamp의 개수를 가져오는 메서드로 분리하는 것이 좋아보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampService.java
> +		}
이러한 부분은 StampBoard 도메인 내에서 책임을 가지고 내부에서 변경하는 게 좋아보여요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/repository/UserRepository.java
> +	Optional<User> findByMemberId(@Param("memberId") long memberId);
이 부분 사용을 안 하는 것 같네요 + MemberRepository가 가져야 할 메서드 같아요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	public ResponseEntity<?> createMissionComplete(
이 부분도 와일드 카드 고려 부탁드려요!

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +		missionService.createMissionComplete(stampBoard, mission, missionCompleteCreateRequest.guardianId(), member);
getMission을 여기서 호출해서 createMissionComplete로 넘기는 이유가 있을까요?

createMissionComplete에서 호출하면 인자가 줄어들 것 같네요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final UserService userService;
MissionController, MissionService 두 곳에서 UserService 참조하고 있네요.

2023-05-21 10:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final StampBoardService stampBoardService;
Controller 단에서 StampBoardService 참조하고 있는 것을 보면, MissionService와 StampBoardService 순환 참조 때문에 Controller에서 참조해서 사용하고 계신건가요?

2023-05-21 10:18 UTC, yeongchan1228 commented on src/test/java/com/polzzak/domain/stamp/controller/StampControllerTest.java
> +		//FIXME jjh anyLong() error -> isNull()
partnerMemberId 값을 param()으로 안 넘겨주셔서 Controller에서 null로 받아서 처리합니다.

`stampBoardService.getFamilyStampBoardSummaries(any(), isNull(), anyBoolean())` 을 
`stampBoardService.getFamilyStampBoardSummaries(any(), anyLong(), anyBoolean())`로 바꾸고, return 값으로 `FAMILY_STAMP_BOARD_SUMMARIES`을 설정해 놓는 경우,

실제 Controller에서는 `stampBoardService.getFamilyStampBoardSummarie("username", null, true)` 로 동작해서 `FAMILY_STAMP_BOARD_SUMMARIES` 값을 return 하지 않아, 응답 결과 파싱에서 에러가 발생해요.

```java
verify(stampBoardService, times(1)).getFamilyStampBoardSummaries(any(), isNull(), anyBoolean()); // true
verify(stampBoardService, times(0)).getFamilyStampBoardSummaries(any(), anyLong(), anyBoolean()); // true
```
위와 같이 테스트 코드를 작성해서 실행해보면 주석과 같은 결과가 나와요.

따라서, `.param("partnerMemberId", xx)`를 추가하시고 `stampBoardService.getFamilyStampBoardSummaries(any(), anyLong(), anyBoolean())`로 작성하시면 에러 없이 실행됩니다.

2023-05-21 15:13 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +	public ResponseEntity<?> createStampBoard(
``` diff
-	public static ApiResponse created() {
+	public static ApiResponse<Null> created() {
		return new ApiResponse(HttpStatus.CREATED.value(), null, null);
	}
```

반환타입을 변경하는 거에 대해 어떻게 생각하실까요?

2023-05-21 15:30 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +		@RequestParam boolean isInProgress
도장판 상태가 4개 있는데요.
크게 3개가 진행 중, 1개가 완료 상태입니다.
필터링이 진행/완료 외에 다른 값이.. 나온다면 수정해야겠지만 우선은 현재 기획에 맞춰 이렇게 진행했습니다.
만약 필터링 조건이 추가된다해도 수정이 어렵지 않을 것 같아서요.

좋은 의견 있으실까요

2023-05-21 15:31 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
수정해두겠습니다.
혹시 책에서 읽으신걸까요? 책에서 보신거면 제목이 궁금합니다

2023-05-21 15:33 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		List<FamilyMemberDto> filteredFamilies = getFilteredFamilies(families, partnerMemberId);
`getFilteredFamilies` -> `getFilteredFamiliesByPartnerId` 이 정도면 어떠실까요

2023-05-21 15:40 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
단순히 파라미터 순서만 바뀌는 거라서 메서드 이해에 큰 영향을 끼치는 로직이 아니고 간단해 보여서 그대로 두려고 합니다.
메소드로 나누면 메소드 내의 코드는 잘 읽힐지 몰라도 상위 메소드의 코드가 다른 메소드에 다 숨어 있으면 그것도 읽기 어려울 것 같아서요

2023-05-21 15:41 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +	}
이 부분은 따로 뺐습니다. `getFilteredStampBoardsByStatus()` 이름이 이상하면 말씀 부탁드려요

2023-05-21 15:50 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
patch로 수정했습니다. if 검사 없이 그대로 업데이트하면 put을 사용해야 되는 건 아닌지 생각이 드네요

2023-05-21 15:55 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/mission/service/MissionService.java
> +		missionRepository.saveAll(newMissions);
이전 미션 모두 삭제 후 설정한 미션 전체 insert 말씀이신가요
장점이 있을까요? 만약 미션을 수정한다면 사용자는 1, 2개 정도만 추가/삭제하지 않을까.. 생각이 듭니다

2023-05-21 15:59 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampService.java
> +				.stampBoard(stampBoardService.getStampBoard(stampBoardId))
아 이 부분 이슈가 있어서 이것저것 수정하다가 남은 코드입니다.
수정했습니다.

2023-05-21 16:12 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final UserService userService;
Controller에서는 유저가 요청 가능한 상태인지 검사하기 위해 member를 가져오고 있고요
Service에서는 entity를 불러오기 위해 사용하고 있습니다.

같은 패키지의 Controller와 Service에서 UserService를 사용하면 안 되는 이유가 있을지 궁금합니다.

2023-05-21 16:13 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final StampBoardService stampBoardService;
네 맞습니다
혹시 좋은 방법이 있으실까요

2023-05-21 16:17 UTC, jihoon-jang commented on src/test/java/com/polzzak/domain/stamp/controller/StampControllerTest.java
> +		//FIXME jjh anyLong() error -> isNull()
감사합니다. 문서에 n명 유저마다의 도장판 정보를 내리기 위해서 null이 적당해보이는데요
anyLong() 사용을 위해 파라미터를 넣으면 혼란이 생길 것 같네요 ㅎㅎ;
이 API 문서에 필터링을 추가한 정보를 넣는다면 참고하겠습니다!

2023-05-21 16:26 UTC, jihoon-jang commented
> 1. @Setter를 사용해서 setXXX()로 Entity의 값을 수정하지 말고, 명확한 메서드를 사용해서 필드 값을 변경하는게 좋아 보이네요. -> setXXX를 사용하면 어떻게 변경되는지 와 닿지 않고 setXXX로 열어 두시면 어디서든 접근해서 변경해버릴 수 있을 것 같아요. 검증 부분도 설정한 메서드에 넣어서 필드 값의 변경 검증 책임을 entity에서 가지고 있는 게 좋아보여요.
> 2. 매개변수 값에 final을 붙여서 사용되는 값의 변경을 막는 게 좋아보이네요.
>    `매개변수를 final로 선언함으로써 인자로 들어온 값에 대한 데이터의 정합성을 유지 할 수 있다.`
> 3. 현재 미션과 스탬프 보드는 같은 생명 주기를 가지고 있는 것 같은데 도메인으로 분리하신 이유가 궁금하네요.

1번의 경우는 도장판 Status 관련 말씀이신지 전체적인 Setter 관련 말씀이신지 궁금합니다.

2번은 이제 작업할 때는 명시해두겠습니다. 작성한 코드에도 붙여두겠습니다.

3번에서 제가 패키지(도메인)를 나누는 기준은 각 패키지의 역할(+ 테이블)에 따라 나누었습니다.
미션을 도장 쪽으로 몰아넣는 것보다 미션과 미션 완료 요청은 분리해두는 것이 패키지의 크기나 역할이 좀 나뉠 것 같아 나누었는데요.
생명 주기에 따라 패키지를 분리한다면 `미션`과 `미션 완료 요청`은 다른 패키지에 존재해야 하는거죠..?
만약 기획이 변경되어 생명 주기도 바뀌게 된다면 패키지도 같이 분리/merge 되는지도 궁금합니다.

2023-05-24 10:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +	public ResponseEntity<?> createStampBoard(
확인해보니 반환 타입을 변경해도 Controller에서 밑줄 쳐지더라고요.. `ResponseEntity<ApiResponse<Void>>` 어떠실까요?

2023-05-24 10:45 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +		@RequestParam boolean isInProgress
RequestDto로 Status를 진행 중이냐, 종료되었냐 2 개 받아서 진행 중이면 `getProgressStatuses()`를 호출하는게 나을 것 같은데 어떠신가요?

Param으로 true/false 값을 넘기는 것보다 나을 것 같아요!

2023-05-24 10:50 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
[링크](https://limdingdong.tistory.com/m/8) 참고 하시면 좋을 것 같아요.

저는 클린 코드 공부하면서 익혔습니다.

2023-05-24 10:50 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
if / else 패턴만 제거해주시고 원하는 방식으로 해주시면 좋을 것 같습니다!

2023-05-24 10:51 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
그대로 덮어쓰면 put이 맞다고 생각합니다.

2023-05-24 10:52 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/service/MissionService.java
> +		missionRepository.saveAll(newMissions);
제가 리뷰를 남겼을 때는 put 메서드를 사용하고 계셨어서,, 이 부분은 편하신대로 하셔도 좋을 것 같아요.

2023-05-24 10:53 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final UserService userService;
같은 도메인의 controller와 service가 같은 userService를 참조하고 있으면 너무 강한 결합이라고 생각해요.
한 곳에서만 참조하면 userService 관련은 한 곳만 신경쓰면 되니깐요!

2023-05-24 10:54 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final StampBoardService stampBoardService;
이 부분은 따로 회의를 통해서 아래 3번 내용과 같이 이야기 나누는 게 좋아 보입니다!

2023-05-24 10:57 UTC, yeongchan1228 commented
1. 넵 모든 Setter입니다. 저는 Setter 사용은 지양했으면 해서요. 이유는 다음과 같습니다.
```
- 다른 사람이 코드를 보거나, 나중에 본인이 짠 코드를 봤을 때, 값을 변경한 의도를 파악하기 어렵기 떄문에 코드를 역추적해야 하는 상황이 발생할 수 있다.
- setter 때문에 의도치 않게 값이 변경될 수 있는 위험이 존재하므로 사전에 차단해야 한다.
```
2. 넵
3. 이 부분도 따로 이야기를 나눠봐야 할 것 같습니다!

2023-05-24 16:43 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +	public ResponseEntity<?> createStampBoard(
네 그러면 create쪽만 수정해둘게요~

2023-05-24 16:55 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/controller/StampController.java
> +		@RequestParam boolean isInProgress
StampBoardGroup enum 생성하여 사용하도록 변경했습니다.

2023-05-24 16:58 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
혹시 if 검사를 안 하고 무조건 update하는 것의 장점이 어떤 것이 있을까요?
DB 리소스보다 서버 리소스를 쓰는 것이 대부분의 경우 맞다고 생각하고 있는데 JPA에서는 다른건지 제가 생각 못한 다른 것이 있는지 궁금합니다~

2023-05-24 17:04 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/mission/controller/MissionController.java
> +	private final UserService userService;
우선 줄줄이 entity를 컨트롤러에서 내리는 것보다 서비스에서 검증할 수 있도록 Controller에서 userService를 제거했는데요..
좀 기괴하게 변했네요

2023-05-24 17:16 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		stampBoardRepository.delete(stampBoard);
이거는 아직 확인 중이라 개선 방법 찾아서 변경하고 resolve하겠습니다.

2023-05-25 03:40 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stamp/service/StampBoardService.java
> +		}
제가 말씀드렸던 상황은 PUT 메서드를 사용했던 상황이였습니다!!

[링크](https://tecoble.techcourse.co.kr/post/2020-08-17-put-vs-patch/) 에서 PUT 메서드의 정의와 사용 방법을 확인해보시면 좋을 것 같아요!

같지 않은지 판단 후 수정 (X) -> `그냥 요청 받은 값으로 조건을 타지 않고 바로 업데이트 한다.` 라는 개념으로 저는 이해하고 있는데 다르게 이해하고 계실까요?

2023-05-29 07:20 UTC, yeongchan1228 approved these changes
고생하셨습니다!👍

2023-05-29 07:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stampboard/controller/StampController.java
StampController보다 StampBoardController가 맞을 거 같아요!

2023-05-29 07:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stampboard/controller/MissionController.java
>  	public ResponseEntity<ApiResponse<Void>> createMissionComplete(
이 부분을 StampBoardController에서 처리하는 건 어떻게 생각하시나요?

`StampBoard 조회 -> getMissions -> missionId가 존재 하는 지 검증 -> 검증이 true면 mission complete 로 처리`

2023-05-29 07:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stampboard/repository/MissionRepository.java
> +	void deleteByIdIn(List<Long> ids);
in 절보다 `where stampboardId = ?` 로 처리하시는 건 어떠실까요??

2023-05-29 10:24 UTC, merged