feat: 사용자 포인트 작업
POLZZAK/POLZZAK-BackEnd pull request #17
Opened 2023-06-29 08:39 UTC by yeongchan1228

# 📒 작업 내용
1. 사용자 포인트 작업 (비동기 이벤트 처리)
2. 사용자 정보(me) 응답 값 조회 수정 (마이페이지에 맞게 응답 값 변경)

# 💬참고 사항
- 쿠폰, 선물 기능이 구현되면 그 후에, 작업을 더 해야 할 것 같네요.

2023-06-29 17:15 UTC, jihoon-jang requested changes
내용 확인 한번 부탁드립니다
바뀐 컨벤션도 숙지해야겠네요

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/service/UserService.java
>  	}
여긴 단순 조회하는 메소드인 것 같은데 `@Transactional`이 붙어 있는 이유가 있을까요?

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/memberpoint/entity/MemberPoint.java
> +	@Id
이 클래스는 BaseEntity를 안 쓴 이유가 있을까요?

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/memberpoint/entity/MemberPoint.java
> +	private int level = 0;
기본값인가요?

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +	private final MemberPointHistoryRepository memberPointHistoryRepository;
여기는 readOnly transactional 어노테이션이 생략인걸까요?

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +	}
MemberPointType을 파라미터로 받는 것은 어떨까요?

2023-06-29 17:15 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +		return MemberPointHistorySliceResponse.from(pointHistorySlice, pageRequest);
page는 파라미터로 받는 것이 아니고 0으로 고정하여 사용하는 건가요?

2023-06-30 00:40 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/service/UserService.java
>  	}
변경하면서 제거했어야 했는데 누락됐네요!

2023-06-30 00:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/memberpoint/entity/MemberPoint.java
> +	@Id
Generate Key가 아닌 memberId를 pk로 사용하고 있습니다~

2023-06-30 00:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/memberpoint/entity/MemberPoint.java
> +	private int level = 0;
네~

2023-06-30 00:44 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +	private final MemberPointHistoryRepository memberPointHistoryRepository;
넵~ 이제부터 트랜잭션 로직이랑 서비스 로직을 분리해보려고 합니다!

2023-06-30 00:44 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +		return MemberPointHistorySliceResponse.from(pointHistorySlice, pageRequest);
넵~ No-Offset 무한 스크롤 방식으로 구현했습니다!

2023-06-30 00:47 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/memberpoint/service/MemberPointService.java
> +	}
초기 MemberPointHistory는 REGISTER Type으로만 초기화 되기 때문에 다른 Type이 들어올 일이 없습니다~ 메서드 명을 수정해야겠네요!

2023-06-30 06:19 UTC, jihoon-jang approved these changes
👍

2023-06-30 06:19 UTC, jihoon-jang commented
서비스/트랜잭션 분리하는 것에 대해 설명을 좀 더 해주실 수 있을까요?

2023-07-01 05:18 UTC, merged