쿠폰 발급 및 조회 API 추가
POLZZAK/POLZZAK-BackEnd pull request #19
Opened 2023-07-12 17:16 UTC by jihoon-jang

# 📒 작업 내용

1. 쿠폰 발급 및 조회 API 추가
2. 도장판 삭제 로직 임시로 수정(hard -> soft)

# 💬참고 사항

- 기존에는 도장판 삭제 시 아예 데이터를 날렸는데, 이제는 is_deleted 컬럼 추가하여 데이터를 날리지 않도록 수정할 예정입니다.
쿠폰 쪽에 도장판 정보를 그대로 내리는 부분이 있어서 수정했는데, 도장판 삭제 로직도 수정할 예정입니다.

2023-07-16 04:03 UTC, yeongchan1228 requested changes
리뷰가 늦어서 죄송합니다! 코멘트 확인 부탁드려요!

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/controller/CouponController.java
> +		@LoginUsername String username, @RequestBody StampBoardForIssueCoupon stampBoardForIssueCoupon
`username` varchar 타입으로 DB에서 조회하는 것보다 `id` bigint 타입으로 조회하는 것이 검색 속도에 이점이 있어서 `LoginId` 어노테이션 사용으로 변경하고 있습니다! 이 부분도 `LoginId` 어노테이션을 사용하는 것으로 변경해주세요!!

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/service/CouponService.java
> +	public void issueCoupon(MemberDto guardian, long stampBoardId) {
`issueCoupon` 이라는 메서드명만 보고 어떤 역할을 하는 메서드인지 이해가 되지 않는 것 같아요..

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/entity/Coupon.java
> +	}
inner 로 사용하시는 이유가 있을까요?

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/service/CouponService.java
> +		return result;
stream().map 을 사용하면 더 간결하고 가독성 좋은 코드로 변경할 수 있을 것 같아요.

```
familyMapService.getMyFamilies(member.memberId()).stream().map(family -> {~~~})
```

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/service/CouponService.java
> +		}
중복 코드네요, 메서드로 분리해서 사용할 수 있을 것 같아요

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/resources/db/migration/V4_add_coupon.sql
V4_ -> V4__ 로 변경하셔야 할 것 같아요.
```
파일명 규칙
V + 버전 + __ + 설명.sql
```

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/stampboard/repository/StampBoardRepository.java
> +	void updateIsDeletedById(Long id, boolean isDeleted);
`Delete 어노테이션`을 사용하면 spring data delete 를 사용할 때, 해당 쿼리로 나가서  Entity에 Delete 어노테이션을 사용하는 건 어떨까요?

2023-07-16 04:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/service/UserService.java
> +		}
이것도 중복 코드네요

2023-07-18 16:56 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/coupon/service/CouponService.java
> +	public void issueCoupon(MemberDto guardian, long stampBoardId) {
쿠폰 발급(생성)을 하는 메소드인데요..
다른 이름이 있을까요?
<img width="690" alt="스크린샷 2023-07-19 오전 1 56 31" src="https://github.com/POLZZAK/POLZZAK-BackEnd/assets/55784520/22818819-3feb-44a9-9301-e2e11f445fe2">

2023-07-18 16:57 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/coupon/entity/Coupon.java
> +	}
lombok 사용하도록 변경했습니다

2023-07-18 17:10 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/service/UserService.java
> +		}
getGuardianInfo()에는 isKid()
getKidInfo() 에는 isNotKid()
검사 중입니다. 혹시 제가 잘못 이해했을까요 ㅎㅎ;

2023-07-19 16:53 UTC, jihoon-jang commented
V4는 crash가 나서 반영하지 못했는데요..
이건 우선 방법을 좀 찾아서 반영해두겠습니다

2023-07-20 01:34 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/coupon/service/CouponService.java
> +	public void issueCoupon(MemberDto guardian, long stampBoardId) {
처음 메서드 명을 봤을 때, `issue` 명사형으로 생각해서 이슈 쿠폰 = 이슈와 관련된 쿠폰이라고 생각이 들었습니다. 쿠폰 발급이 결국 쿠폰을 생성해서 DB에 저장하는 로직이니깐 생성 쪽이 더 맞다고 생각드네요.. @jihoon-jang  님이 편하신대로 가시죠.

2023-07-20 01:37 UTC, yeongchan1228 commented
V4 파일 변경되면 머지 진행하는 게 나을 것 같네요.

2023-07-23 15:30 UTC, jihoon-jang commented
@yeongchan1228 님 이것저것 해보다가 안 돼서 오래 걸렸는데..
IDE 껐다 켜니 빌드가 되네요;;
아무튼 이름 변경했습니다.

2023-07-24 00:01 UTC, yeongchan1228 approved these changes
네 고생하셨습니다.

2023-07-24 02:48 UTC, merged