feat: 로그인 및 회원가입 기능 구현
POLZZAK/POLZZAK-BackEnd pull request #4
Opened 2023-05-01 11:43 UTC by yeongchan1228

# 작업 내용
1. AWS S3 연결 및 프로필 업로드, 조회, 삭제 기능
2. Jwt 인증 작업
3. 예외 처리 및 API 응답 고도화
4. 소셜 로그인(구글, 카카오) 기능
5. 회원가입 기능
6. 사용자 조회 기능
7. Controller 테스트 고도화

# 참고 사항
작업을 한 번에 진행해서 코드가 많네요... 천천히 해주셔도 됩니다!

2023-05-01 17:09 UTC, jihoon-jang requested changes
양이 너무 많아서 눈에 보이는 것만 코멘트 남겼는데 확인 부탁드려요~
테이블 관련해서도 논의할 것이 있어 보입니다.

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/AmazonS3Service.java
> +        objectMetadata.setContentType(image.getContentType());
코드상으로는 image를 upload하는 것 같은데 메소드명이 uploadFile이라 헷갈립니다

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/AmazonS3Service.java
> +    }
lombok을 이용하지 않는 이유가 있을까요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/FileService.java
> +    }
코드를 보지 않고 메소드명으로 기능이 파악되도록 변경하면 좋을 것 같아요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/support/constant/FileType.java
> +    PROFILE("프로필");
PROFILE_IMAGE로 변경하면 좋을 것 같아요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/properies/AmazonS3Properties.java
> +package com.polzzak.application.properies;
패키지명에 오타가 있어요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/security/JwtProperties.java
> +    }
JwtProperties가 언제 사용되나요?
key, type이 null인 경우 따로 체크해야 하는 이유가 궁금합니다.
null인 경우 따로 값을 넣어줘야 한다면 상수로 관리하는 것이 좋을 것 같아요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/security/LoginUsernameResolver.java
> +    }
이 부분 예외 처리는 되어 있을까요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
인터페이스를 쓰거나 메소드로 따로 빼는 방식을 사용하면 중복된 코드를 줄일 수 있을 것 같아요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
검사를 하는 메소드면 isValid~~가 더 적절하지 않을까요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
메소드명 수정이 필요해 보입니다!

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
여기서 말하는 username이 언제 사용되나요?
username 단어만 놓고 보면 사용자 이름인데 socialType이랑 id를 섞는게 이상해 보여요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/properies/GoogleOAuthProperties.java
> +}
인터페이스 적용은 검토해 보셨을까요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/Member.java
> +    private MemberType memberType;
15자는 좀 빡빡해 보이는데 음.. 넉넉히 30자 정도는 어떨까요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/MemberType.java
> +
개행 기준이 어떻게 되나요?
삼촌에 오타가 있습니다
MemberType에 KID는 없나요?

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/UserRepository.java
> +    Optional<Long> existsByNickname(@Param("nickname") String nickname);
예약어는 대문자로 쓰는 게 눈에 잘 띌 것 같아요

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
버전 관련해서 논의가 필요해 보입니다

2023-05-01 17:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
이런 로직은 아래 layer로 내리는 것이 좋아 보입니다.

2023-05-02 04:13 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/AmazonS3Service.java
> +        objectMetadata.setContentType(image.getContentType());
@jihoon-jang  image -> file로 수정했습니다~

2023-05-02 04:19 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/AmazonS3Service.java
> +    }
해당 클래스가 다른 클래스와 얼마나 강하게 결합되어 있는지 생성자를 통해 직관적으로 알아보기 쉽기 때문에, Service 클래스에서는 @RequiredArgsConstructor 사용을 하지 않았습니다.

개발자 생각 차이이고 @jihoon-jang 님은 Lombok 쓰셔서 개발해도 크게 상관 없을 듯 합니다.

2023-05-02 04:19 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/FileService.java
> +    }
getExtension()으로 수정했습니다~

2023-05-02 04:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/support/constant/FileType.java
> +    PROFILE("프로필");
넵~ 수정했습니다!

2023-05-02 04:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/properies/AmazonS3Properties.java
> +package com.polzzak.application.properies;
아고,, 오타 지적 감사합니다!!!!

2023-05-02 04:22 UTC, yeongchan1228 commented on src/main/java/com/polzzak/security/JwtProperties.java
> +    }
JwtProperties는 Jwt에 사용되는 값들을 yml 파일에서 가져오는데 사용합니다.

테스트 코드에서는 해당 값을 가져오지 않기 떄문에, null 참조가 일어나서 ""을 넣어줬습니다.
key 값의 경우 해시 알고리즘의 key는 일정 길이가 되어야 하기 때문에 대충 넣어놨습니다. 중요한 값은 아니고 더미 데이터라 상수로 뺄 필요는 없는 것 같아요~

2023-05-02 04:22 UTC, yeongchan1228 commented on src/main/java/com/polzzak/security/LoginUsernameResolver.java
> +    }
Advice에서 예외 받아서 처리합니다...

2023-05-02 04:30 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
1. OAuthProperties 들을 하나의 추상 클래스로 묶었을 때, 결국 SocialType에 따라 if 문을 타고 다운 캐스팅해서 진행해야 해서 메서드 별로 나눴습니다. 인터페이스나 다른 메서드로 빼서 구현한 좋은 방법이 있다면 공유해주세요!
2. 아직 애플 소셜 로그인을 구현하지 않아 이후 로직이 어떻게 될 지 몰라서 메서드 별로 구분해서 구현했습니다.

2023-05-02 04:31 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
isValid~ 형식은 boolean 값을 리턴해야 한다고 생각합니다. 해당 로직은 void이고 유효하지 않을 시 바로 예외를 던지기 땜문에 현재 메서드가 맞는 것 같습니다.

2023-05-02 04:32 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
bearerToken() -> getBearerToken() 동사 형식으로 수정했습니다~

2023-05-02 04:33 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
spring security에서는 username = id와 같은 형식으로 사용되고 있어, 사용자를 구분하는 사용자 identifier로 username을 사용하고 있습니다.

사용자를 식별하는 형식으로 만들어주는 메서드라고 보시면 될 것 같습니다.

2023-05-02 04:37 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/properies/GoogleOAuthProperties.java
> +}
1. 적용하더라도 인터페이스가 아니라 추상 클래스를 적용해야 하지 않을까요?
2. configuration-processor 에서는 위 형식처럼 명확하게 perfix를 설정해서 어느 부분을 주입 받을 지, 정하고 필드명도 동일해야 합니다.
3. 추상 클래스로 공통 부분을 묶어서 사용해도 결국은 소셜 타입에 맞게, if, switch 문을 통해서 원하는 값으로 다운 캐스팅해서 써야 한다고 생각합니다. 이 부분을 추상화하려고 해봤지만 현재 형식이 가장 가동성있게 코딩이 된 거 같아서 채용했습니다. 

제가 잘못 생각하고, 제대로 사용하지 않은 것일  수도 있어서 @jihoon-jang 님이 생각하신 방법으로 구현 후, 공유 부탁드려도 될까요?

2023-05-02 04:37 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/Member.java
> +    private MemberType memberType;
수정 했습니다~

2023-05-02 04:38 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/MemberType.java
> +
수정 했습니다~

개행 기준은 codestyle 설정 후, 전체적으로 코드 형식 맞출 생각입니다~

2023-05-02 04:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/UserRepository.java
> +    Optional<Long> existsByNickname(@Param("nickname") String nickname);
JPQL에서는 엔티티를 대문자로 사용해야 하기 때문에, 오히려 예약어를 대문자로 쓰면 가독성이 더 떨어질 것 같습니다.

2023-05-02 04:41 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
어떻게 생각하시죠???

2023-05-02 04:44 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
Presentation Layer에서 사용하는 HttpServletResponse나 ResponseEntity 같은 객체를 Application Layer로 공유하게 되면 두 Layer간 결합도가 생기고, 현재 사용 중인 프로젝트 구조는 데이터 흐름이 단 방향으로 흘러야 하기 때문에 현재 위치에 구현했습니다.

2023-05-02 06:03 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/MemberType.java
> +
@yeongchan1228 님 enum은 한 줄에 담기면 한 줄로 쓰고 넘어가면 하나마다 개행하는 것은 어떻게 생각하시나요?

2023-05-02 06:04 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
@yeongchan1228 님 그러면 validateNickname으로 변경해야 할 것 같아요

2023-05-02 06:14 UTC, yeongchan1228 commented on src/main/java/com/polzzak/domain/user/MemberType.java
> +
음... 이 부분에 대해서는 google, naver 코드 컨벤션 확인 후 적용하면서 따로 말씀드릴게요!

2023-05-02 06:14 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
수정했습니다~

2023-05-02 06:18 UTC, jihoon-jang commented on src/main/java/com/polzzak/domain/user/MemberType.java
> +
@yeongchan1228 님 아, 네네 확인 후 더 좋은 방법이 있으면 공유 부탁드릴게요

2023-05-02 06:47 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
@yeongchan1228 님 [semantic version](https://otrodevym.tistory.com/entry/%EB%B2%84%EC%A0%84%EA%B4%80%EB%A6%AC-Semantic-Versioning%EC%8B%9C%EB%A7%A8%ED%8B%B1-%EB%B2%84%EC%A0%84%EA%B4%80%EB%A6%AC%EC%99%80-Version-Ranges) 정도로 생각 중이었는데
큰 변경 사항이 없을 것 같아 minor version(v1.0) 까지만 사용하는 것은 어떨까요?

2023-05-02 06:59 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
@jihoon-jang 네 저도 좋다고 생각합니다!

minor version을 적용해서 uri 경로는 /api/v1/* 그대로 하겠습니다.
1.x 버전은 v1으로 2.x 같이 신 버전이 되면 api/v2/* 식으로 올려가죠!

2023-05-02 07:01 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
@yeongchan1228 님 minor version은 path variable로 빼야 하지 않을까요..?
/v1.{minor_version}/api

2023-05-02 07:03 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
1.x 버전은 1로 통일 시켜도 상관 없지 않나요?
세부적으로 나눠야 하는 이유를 알 수 있을까요???

2023-05-02 07:09 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
@yeongchan1228 님 혹시 버전을 어떻게 나누실지 생각해 두신 것이 있을까요?
API 버전을 명시적으로만 올릴 계획이셨을지 궁금합니다!
앱 같은 경우는 업데이트를 하지 않으면 구 버전 API를 계속 제공해야 해서 나누려고 합니다.

2023-05-02 07:18 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
1.1, 1.2, 1.3 등의 버전 업 과정에서 발생하는 변경 사항들은 모두 v1 API에 적용하고 최신 버전 상태로 배포해서 최신 버전의 API만 제공하고자 했습니다.

앱 같은 경우 현재 버전이 1.5v인데 1.3v를 쓰는 경우, 업데이트를 하도록 실행 시, 팝업을 띄워서 막으면 되지 않을까요??

2023-05-02 07:23 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
@yeongchan1228 님 네 그것도 방법인데 기획에 문의해 볼게요
이해가 잘 안 되는데 major version만 쓰는 것이랑 무슨 차이가 있나요?

v1.1, v1.2 -> v1 이렇게 쓸 것이란 뜻이죠?

2023-05-02 07:24 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +public class UserRestController {
명시적으로는 나누고, 실제 구현으로는 V1으로 통일하려고 했습니다.

2023-05-02 14:49 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
다시 생각해봤는데 Application Layer로 내리는 것이 좋을 것 같습니다.
Layer간 결합도는 존재할 수 밖에 없는데 HttpServletResponse나 ResponseEntity가 왔다갔다한다고 결합도가 더 강하게 생기는 것이 아니지 않나요.
ResponseEntity같은 경우는 getTokenResponseEntity()가 TokenResponse를 반환하도록 변경하면 될 문제 아닐까요?

데이터가 단방향으로 흐른다는 것은 밑에서 위를 참조하지 못하는 것을 의미하는 게 아닌가요?

2023-05-02 14:51 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/properies/GoogleOAuthProperties.java
> +}
추상 클래스를 어떻게 적용하신다는건지 설명 가능하실까요?
설정값 읽어서 가져오는 것을 못 봤네요 ㅎㅎ;

필드가 없는 interface라도 묶어두면 좋을 것 같아요

2023-05-02 14:55 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/UserAuthenticationService.java
> +    }
잠깐 봤을 때 인터페이스 적용하면 깔끔해질 것 같았는데 설정 파일이 엮여있다 하셔서 개선이 어렵네요..
우선 이대로 두고 나중에 차차 개선해보면 좋을 것 같아요~

2023-05-02 15:06 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
Application Layer로 내린다면 어떤 서비스에서 해당 메서드의 역할을 해야 할까요?
현재 토큰에 대한 응답값을 받아오는 로직은 userAuthenticationService.generateAccessTokenByUsername(username)에서 진행하고 있으며, 해당 컨트롤러의 메서드는 사용자에게 응답할 데이터 객체인 TokenResponse로 포장하고, ResponseEntity로 감싸는 행위만 하고 있습니다. ResponseEntity의 경우 클라이언트에게 반환될 상태 코드나 response body 값을 가지고 있기 때문에 application layer보다는 presentation layer가 해야 하는 일에 가깝다고 생각을 했어요.

만약 application layer가 responseEntity나 HttpServletResponse 같은 클래스를 의존하게 된다면, 기존에 작성하였던 getUserInfo 같은 메서드도 userService.getUserInfo()에서 ResponseEntity<ApiResponse>을 반환하는 구조로 가야 할 것입니다. 그렇다면 presentation layer가 하는 일은 단순히 application layer가 반환한 값에 대해 그대로 반환하는 역할밖에 하지 않겠죠. 각 layer가 어떤 책임을 가지고 있는지에 따라 의존해야 하는 객체가 다르다고 생각합니다.

단순히 Layer 간의 결합도 보다 각 Layer가 어떤 책임을 가지고 있는지에 따라서 코드 설계 방향이 달라질 것 같은데, 어떤 이유로 Application Layer로 내리는 게 좋을 것 같다고 생각하셨나요?

2023-05-02 15:09 UTC, yeongchan1228 commented on src/main/java/com/polzzak/application/properies/GoogleOAuthProperties.java
> +}
인터페이스는 공통적인 행동 규약을 정의하기 위해서 사용하는데, 현재 필드값에 대한 생성자 바인딩만 존재하는 클래스에서 어떤 식으로 인터페이스를 적용하라고 말씀하시는 건지 잘 이해가 가지 않습니다. 지훈님이 생각하신 인터페이스 적용 방식에 대해서 말씀해 주실 수 있나요?

2023-05-02 15:19 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
`컨트롤러의 메서드는 사용자에게 응답할 데이터 객체인 TokenResponse로 포장하고, ResponseEntity로 감싸는 행위만 하고 있습니다. ` -> 이건 API 받는 컨트롤러 메소드에서 처리하거나 공통으로 처리하고 싶으면 TokenResponse의 메소드를 호출하면 될 것 같습니다.

`presentation layer가 하는 일은 단순히 application layer가 반환한 값에 대해 그대로 반환하는 역할` -> 컨트롤러에서 할 일이 없다면 그냥 반환해도 상관없지 않나요? 지금 케이스에서는 ResponseEntity로 변환하는 역할을 하면 될 것 같아요.

저는 컨트롤러에서 url mapping된 메소드 이외의 메소드를 본 적이 없습니다. 컨트롤러의 역할이 요청을 받아서 요청을 내보내는 건데 login(), addRefreshCookie()처럼 비지니스 로직이 끼어있는 메소드는 아래 Layer로 내리는 것이 맞다고 봅니다.

개선 방향
1. HttpServletResponse 관련 ->  response.addCookie()를 컨트롤러에서 호출하면 되지 않나요? 쿠키값을 Application(Service)에서 반환해주면 될 것 같아요
2. ResponseEntity 관련 -> 200응답은 컨트롤러에서 만들고, 그 외 응답은 예외 처리 Handler에서 내보내면 될 것 같습니다!

2023-05-02 15:20 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
<img width="622" alt="스크린샷 2023-05-03 오전 12 19 39" src="https://user-images.githubusercontent.com/55784520/235710561-582b9ce5-61a7-4dea-915b-351262bd2813.png">

컨트롤러의 역할은 위 역할 정도면 충분하다고 생각됩니다 ㅎㅎ;

2023-05-02 15:25 UTC, jihoon-jang commented on src/main/java/com/polzzak/application/properies/GoogleOAuthProperties.java
> +}
다시 생각해 보니 인터페이스로 묶더라도 활용이 어려울 것 같네요.
말씀 감사합니다~

2023-05-02 15:29 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
저는 클라이언트에 응답을 다시 보내는 역할 = 클라이언트에게 반환할 response header, body 값을 설정해주는 역할이라고 생각합니다. 
`addRefreshCookie`의 경우 비즈니스 로직보다, 클라이언트에게 응답으로 반환할 값을 세팅해주는 메서드라고 생각합니다. 위에서 첨부하신 자료에서 '사용자 요청에 대해 해석하고 응답하는 일을 책임지는 계층이다' 라는 부분과 대응되는 말인 것 같네요. 왜 밑줄친 부분만 역할을 해야 한다고 하셨을까요? 

지훈님은 컨트롤러에서 url mapping된 메서드 이외의 다른 메서드를 본 적이 없다고 말씀해 주셨지만, 이 경우 대부분 비즈니스 로직에서 반환되는 값들을 그대로 클라이언트에게 응답으로 반환해주기 때문에 그랬을 것이라고 생각합니다. 현재의 요청에서는 body 값 이외에 header의 값을 설정하는 단계이기 때문에 클라이언트에게 응답하는 일이라고 볼 수 있을 것 같습니다. 컨트롤러에서 다른 메서드가 들어가면 안 된다는 레퍼런스나 자료 있을까요?

지훈님이 정의하신 Presentation Layer의 역할이 궁금합니다.

2023-05-02 16:02 UTC, jihoon-jang commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
네 응답에 포함될 값을 세팅하는 게 컨트롤러의 역할이 맞습니다.
다만 기타 메소드가 컨트롤러에 추가된 것에 대해 말씀드린거고요.. 그래서 제가 메소드 일부를 컨트롤러 로직에 넣으면 될 것 같다고 말씀드렸어요. Application Layer로 내리면 좋을 것 같다는 말에 오해가 있으신 것 같네요

컨트롤러에 다른 메소드가 존재하면 안 된다고 정의된 자료는 본 적이 없는 것 같은데 대부분 매핑 메소드만 두는 것 같습니다.
이거에 대해서도 영찬님처럼 작업이 된 코드나 자료가 있을지 궁금합니다.

저는 말씀드린대로 컨트롤러에는 매핑 메소드만 존재해야 한다고 생각하고 있어요.
ResponseEntity, HttpResponse에 너무 엮여있는 것 같은데 이게 찝찝하시면 제가 제안드린 방법을 참고하시면 될 것 같습니다.
Service 단에 어울리지 않는 로직은 관련 클래스에 static method 등으로 정의하여 사용하면 될 것 같아요.

제가 말씀드린 방법 중 어색하다고 느끼시거나 아니면 다른 생각이 있으신지 궁금합니다~

2023-05-02 16:20 UTC, yeongchan1228 commented on src/main/java/com/polzzak/presentation/api/UserRestController.java
> +    }
```java
Cookie refreshTokenCookie = new Cookie(REFRESH_TOKEN_HEADER, userAuthenticationService.generateRefreshTokenByUsername(payload));
refreshTokenCookie.setHttpOnly(true);
```

지훈님은 이 부분을 application layer로 내리고, 쿠키값을 받아서 response에 넣는 것을 컨트롤러에서 진행하는 방법을 제안해주셨어요. Cookie 클래스는 servlet 측에서 제공하고 있습니다. (실제로 패키지 구조를 확인해보시면 `jakarta.servlet.http.Cookie`로 import 되어 있는 것을 볼 수 있어요) 서블릿은 http request - response를 관리하는 기능을 제공하고 있기 때문에, presentation layer에서 책임을 가지는 클래스라고 생각합니다. 단순히 ResponseEntity, HttpResponse에 엮여 있어서 말씀을 드리는 게 아니라, servlet과 관련 있는 클래스를 application layer까지 끌어내려 관리하는 게 어색하다고 느껴졌습니다. layered architecture를 채택한 이상, 각 레이어가 담당하고 있는 역할은 명확하게 해야 한다고 생각합니다.

기타 메서드로 분리한 이유는 loginKakao, loginGoogle 메서드에서 공통적으로 진행하는 행위이기 때문에 분리한 것입니다. 사실상 두 메서드의 중복 처리를 진행하지 않는다면 loginKakao, loginGoogle에서 각각 시행될 로직일 것이고, 이 로직들은 servletResponse와 관련있기 때문에 controller에서 처리하는 것이구요. 

그리고 관련 클래스는 어떤 것을 말씀하시는 것일까요? 단순히 쿠키를 추가하기 위한 CookieService 같은 것을 만든다면, 쿠키에 응답을 담아주는 모든 컨트롤러에서는 해당 서비스에 대해 의존성을 가지고 있어야 할까요? 저는 오히려 이런 부분들은 각 클래스간의 결합도를 높인다고 생각됩니다. static method로 분리해서 관리할 필요성도 느끼지 못했구요.

컨트롤러에서 다른 메서드가 존재하면 안 된다고 정의된 자료가 없다면 코드 자체에 정답이 없다는 말이라고 생각됩니다. 
매핑 메서드 외의 다른 메서드가 있는 것 자체가 어색하다고 느껴지신다면 중복 코드를 제거하지 않고 매핑 메서드에서 각각 정의하는 식으로 리팩터링을 진행할까요?

현재 채택한 구조가 그러한 일부분의 결합을 허용하는 게 아니라서요 ㅎㅎ mvc -> mvp -> mvvm 패턴으로 계속해서 나오는 이유를 생각해보시면 좋을 것 같습니다!
그런 방식으로 진행하고 싶으시면 다른 구조를 채택해서 패키지 구조부터 엎어버리고 다시 개발 진행하는 게 좋을 것 같습니다!

지훈님이 진행하시고 계시거나 진행하셨던 아키텍처 구조와 디자인 패턴 알려주시면 그 방법대로 하겠습니다! 레퍼런스 자료 첨부해주세요!

2023-05-03 05:48 UTC, jihoon-jang approved these changes

2023-05-03 05:48 UTC, merged